// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaptySTqnmx11VVOm1pCfZPM7NR6sTFMQ',
    appId: '1:1028245076872:web:f8a2e9d2e201dbd8c6d83d',
    messagingSenderId: '1028245076872',
    projectId: 'authfinal-2fc4e',
    authDomain: 'authfinal-2fc4e.firebaseapp.com',
    storageBucket: 'authfinal-2fc4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-XcOq_XWVbV3tkdvPW_a2BIXOycF2KDM',
    appId: '1:1028245076872:android:cada5ab00eb84d03c6d83d',
    messagingSenderId: '1028245076872',
    projectId: 'authfinal-2fc4e',
    storageBucket: 'authfinal-2fc4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFjtLv4Xq0N9Vb9mmjN7O3PbU3OG-yoQ',
    appId: '1:1028245076872:ios:8df8112d97accea6c6d83d',
    messagingSenderId: '1028245076872',
    projectId: 'authfinal-2fc4e',
    storageBucket: 'authfinal-2fc4e.appspot.com',
    iosBundleId: 'com.example.addapp',
  );
}
